window.SEARCH_INDEX = [
  {
    title: "Kathmandu Valley Travel Guide",
    category: "Destination",
    description:
      "Three historic cities, layered neighbourhoods and living ritual—best understood one courtyard at a time.",
    url: "/destinations/kathmandu-valley",
    tags: [
      "Kathmandu Valley",
      "Bagmati",
      "Living heritage",
      "Patan",
      "Bhaktapur",
      "Boudhanath",
      "Swayambhunath",
      "Kirtipur",
      "Panauti",
    ],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Pokhara Travel Guide",
    category: "Destination",
    description:
      "A lakeside city where Himalayan mornings open into ridge walks, paddling, neighbourhood food and unhurried afternoons.",
    url: "/destinations/pokhara",
    tags: [
      "Pokhara",
      "Gandaki",
      "Lakes & adventure",
      "Phewa Lake",
      "Sarangkot",
      "Begnas Lake",
      "Old Bazaar",
      "Peace Pagoda",
      "Hemja Valley",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Everest Region Travel Guide",
    category: "Destination",
    description:
      "The Khumbu is not one viewpoint but a lived mountain landscape of Sherpa villages, monasteries and high valleys.",
    url: "/destinations/everest-region",
    tags: [
      "Everest Region",
      "Koshi",
      "High Himalaya",
      "Lukla",
      "Namche Bazaar",
      "Khumjung",
      "Tengboche",
      "Gokyo",
      "Dingboche",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Annapurna Region Travel Guide",
    category: "Destination",
    description:
      "A web of trails links subtropical valleys, rhododendron forest, Gurung villages and the high desert beyond Thorong La.",
    url: "/destinations/annapurna-region",
    tags: [
      "Annapurna Region",
      "Gandaki",
      "Village trekking",
      "Ghandruk",
      "Chhomrong",
      "Manang",
      "Marpha",
      "Jomsom",
      "Muktinath",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Chitwan Travel Guide",
    category: "Destination",
    description:
      "Riverine forest and tall grasslands reveal a lowland Nepal of rhinos, birds, gharials and Tharu heritage.",
    url: "/destinations/chitwan",
    tags: [
      "Chitwan",
      "Madhesh–Bagmati lowlands",
      "Wildlife & Tharu culture",
      "Sauraha",
      "Bharatpur",
      "Meghauli",
      "Rapti River",
      "Community forests",
      "Bishazari Tal",
    ],
    image: "/assets/nepal-chitwan.webp",
  },
  {
    title: "Lumbini Travel Guide",
    category: "Destination",
    description:
      "The birthplace of the Buddha is a quiet landscape of archaeology, gardens and living monastic traditions.",
    url: "/destinations/lumbini",
    tags: [
      "Lumbini",
      "Lumbini Province",
      "Sacred heritage",
      "Sacred Garden",
      "Maya Devi Temple",
      "Monastic Zone",
      "Tilaurakot",
      "Kudan",
      "Devdaha",
    ],
    image: "/assets/nepal-lumbini.webp",
  },
  {
    title: "Upper Mustang Travel Guide",
    category: "Destination",
    description:
      "A trans-Himalayan world of walled settlements, cave complexes, wind-carved cliffs and Tibetan Buddhist culture.",
    url: "/destinations/upper-mustang",
    tags: [
      "Upper Mustang",
      "Gandaki",
      "Restricted high desert",
      "Lo Manthang",
      "Tsarang",
      "Ghami",
      "Chhoser",
      "Kagbeni",
      "Jomsom",
    ],
    image: "/assets/nepal-mustang.webp",
  },
  {
    title: "Rara Lake Travel Guide",
    category: "Destination",
    description:
      "Nepal’s largest lake rests among pine ridges in Karnali, far beyond the country’s familiar travel corridors.",
    url: "/destinations/rara-lake",
    tags: [
      "Rara Lake",
      "Karnali",
      "Remote lake & forest",
      "Rara Lake",
      "Murma Top",
      "Talcha",
      "Gamgadhi",
      "Salleri area",
      "Rara National Park",
    ],
    image: "/assets/nepal-rara.webp",
  },
  {
    title: "Langtang Travel Guide",
    category: "Destination",
    description:
      "A compact Himalayan valley north of Kathmandu, rebuilt through community effort and best travelled with time to listen.",
    url: "/destinations/langtang",
    tags: [
      "Langtang",
      "Bagmati Himal",
      "Accessible mountain valley",
      "Syabrubesi",
      "Lama Hotel",
      "Langtang Village",
      "Kyanjin Gompa",
      "Tserko Ri area",
      "Tamang Heritage Trail",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Manaslu Travel Guide",
    category: "Destination",
    description:
      "A demanding circuit follows the Budhi Gandaki from warm valleys to Tibetan-influenced villages and Larkya La.",
    url: "/destinations/manaslu",
    tags: [
      "Manaslu",
      "Gandaki Himal",
      "Restricted circuit",
      "Machha Khola",
      "Jagat",
      "Namrung",
      "Samagaun",
      "Samdo",
      "Dharapani",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Gosaikunda Travel Guide",
    category: "Destination",
    description:
      "A chain of sacred alpine lakes sits above forest and Tamang villages on a high route between Langtang and Helambu.",
    url: "/destinations/gosaikunda",
    tags: [
      "Gosaikunda",
      "Langtang, Bagmati",
      "Sacred alpine lakes",
      "Dhunche",
      "Thulo Syabru",
      "Chandanbari",
      "Laurebina",
      "Gosaikunda Lake",
      "Ghopte",
    ],
    image: "/assets/nepal-rara.webp",
  },
  {
    title: "Bandipur Travel Guide",
    category: "Destination",
    description:
      "A preserved hill bazaar turns the Kathmandu–Pokhara journey into a place worth pausing.",
    url: "/destinations/bandipur",
    tags: [
      "Bandipur",
      "Gandaki hills",
      "Historic hill town",
      "Bandipur Bazaar",
      "Tundikhel",
      "Siddha Cave",
      "Ramkot",
      "Thani Mai area",
      "Dumre",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Nagarkot Travel Guide",
    category: "Destination",
    description:
      "A forested ridge gives the Kathmandu Valley breathing room—and, in clear weather, a long Himalayan horizon.",
    url: "/destinations/nagarkot",
    tags: [
      "Nagarkot",
      "Kathmandu Valley rim",
      "Himalayan viewpoints",
      "Nagarkot ridge",
      "View tower area",
      "Changu Narayan",
      "Telkot",
      "Bhaktapur",
      "Sankhu",
    ],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Janakpur Travel Guide",
    category: "Destination",
    description:
      "A sacred city of bright temple architecture, Mithila painting and the living story of Sita.",
    url: "/destinations/janakpur",
    tags: [
      "Janakpur",
      "Madhesh",
      "Mithila culture & pilgrimage",
      "Janaki Mandir",
      "Ram Mandir",
      "Dhanush Sagar",
      "Ganga Sagar",
      "Mithila art centres",
      "Dhanushadham",
    ],
    image: "/assets/nepal-lumbini.webp",
  },
  {
    title: "Ilam Travel Guide",
    category: "Destination",
    description:
      "Green ridges, tea gardens and misty market towns introduce Nepal’s quieter eastern hills.",
    url: "/destinations/ilam",
    tags: [
      "Ilam",
      "Koshi hills",
      "Tea country",
      "Ilam Bazaar",
      "Kanyam",
      "Fikkal",
      "Antu Danda",
      "Mai Pokhari",
      "Sandakpur approaches",
    ],
    image: "/assets/nepal-chitwan.webp",
  },
  {
    title: "Muktinath Travel Guide",
    category: "Destination",
    description:
      "A sacred Himalayan site brings Hindu and Buddhist traditions together above the Kali Gandaki valley.",
    url: "/destinations/muktinath",
    tags: [
      "Muktinath",
      "Mustang, Gandaki",
      "Pilgrimage & high desert",
      "Muktinath Temple",
      "Ranipauwa",
      "Kagbeni",
      "Jomsom",
      "Marpha",
      "Lubra",
    ],
    image: "/assets/nepal-mustang.webp",
  },
  {
    title: "Tansen / Palpa Travel Guide",
    category: "Destination",
    description:
      "A steep, lived-in hill town of courtyards, metalwork, woven dhaka and far-reaching ridge views.",
    url: "/destinations/tansen",
    tags: [
      "Tansen / Palpa",
      "Lumbini hills",
      "Hill town & craft",
      "Tansen Bazaar",
      "Srinagar Hill",
      "Rani Mahal",
      "Bhagwati Temple",
      "Amar Narayan area",
      "Palpa villages",
    ],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Khaptad Travel Guide",
    category: "Destination",
    description:
      "Rolling high meadows, forest and sacred places form one of far-west Nepal’s least hurried landscapes.",
    url: "/destinations/khaptad",
    tags: [
      "Khaptad",
      "Far West",
      "High meadows & forest",
      "Khaptad Patan",
      "Khaptad Baba area",
      "Triveni",
      "Silgadhi",
      "Bajhang approaches",
      "Community villages",
    ],
    image: "/assets/nepal-rara.webp",
  },
  {
    title: "Kanchenjunga Travel Guide",
    category: "Destination",
    description:
      "Long approaches and vast valleys lead toward the world’s third-highest mountain in Nepal’s far east.",
    url: "/destinations/kanchenjunga",
    tags: [
      "Kanchenjunga",
      "Koshi Himal",
      "Remote high trekking",
      "Taplejung",
      "Sekathum",
      "Ghunsa",
      "Kambachen",
      "Pangpema",
      "Tseram",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Dolpo / Phoksundo Travel Guide",
    category: "Destination",
    description:
      "Turquoise Phoksundo and the austere valleys beyond open one of Nepal’s most remote journeys.",
    url: "/destinations/dolpo-phoksundo",
    tags: [
      "Dolpo / Phoksundo",
      "Karnali Himal",
      "Remote lake & trans-Himalaya",
      "Juphal",
      "Dunai",
      "Chhepka",
      "Ringmo",
      "Phoksundo Lake",
      "Shey area",
    ],
    image: "/assets/nepal-rara.webp",
  },
  {
    title: "Everest Base Camp Trek",
    category: "Trek",
    description:
      "A high-altitude journey through Sherpa country to the foot of the Khumbu Icefall, paced around acclimatisation rather than speed.",
    url: "/treks/everest-base-camp",
    tags: [
      "Everest",
      "12–16 days",
      "Challenging",
      "Lukla",
      "Phakding",
      "Namche Bazaar",
      "Tengboche",
      "Dingboche",
      "Lobuche",
      "Gorak Shep",
      "Everest Base Camp",
      "Kala Patthar",
      "Pheriche",
      "Namche Bazaar",
      "Lukla",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Everest View Trek",
    category: "Trek",
    description:
      "A shorter Khumbu route centred on Namche, Khumjung and mountain viewpoints without continuing to base camp.",
    url: "/treks/everest-view",
    tags: [
      "Everest",
      "5–8 days",
      "Moderate",
      "Lukla",
      "Phakding",
      "Namche Bazaar",
      "Khumjung",
      "Everest View area",
      "Monjo",
      "Lukla",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Gokyo Lakes Trek",
    category: "Trek",
    description:
      "A quieter high-valley route to turquoise lakes and a panoramic summit above the Ngozumpa Glacier.",
    url: "/treks/gokyo-lakes",
    tags: [
      "Everest",
      "12–15 days",
      "Challenging",
      "Lukla",
      "Namche Bazaar",
      "Dole",
      "Machhermo",
      "Gokyo",
      "Gokyo Ri",
      "Dole",
      "Namche Bazaar",
      "Lukla",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Everest Three Passes Trek",
    category: "Trek",
    description:
      "The Khumbu’s most complete teahouse circuit links three high passes, Gokyo and the base-camp valley.",
    url: "/treks/three-passes",
    tags: [
      "Everest",
      "17–21 days",
      "Very challenging",
      "Lukla",
      "Namche Bazaar",
      "Chhukung",
      "Kongma La",
      "Lobuche",
      "Everest Base Camp",
      "Cho La",
      "Gokyo",
      "Renjo La",
      "Thame",
      "Namche Bazaar",
      "Lukla",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Annapurna Circuit Trek",
    category: "Trek",
    description:
      "A classic long-distance route across climate zones and Thorong La, now best planned around changing road sections.",
    url: "/treks/annapurna-circuit",
    tags: [
      "Annapurna",
      "12–18 days",
      "Challenging",
      "Besisahar",
      "Dharapani",
      "Chame",
      "Pisang",
      "Manang",
      "Yak Kharka",
      "Thorong Phedi",
      "Thorong La",
      "Muktinath",
      "Jomsom",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Annapurna Base Camp Trek",
    category: "Trek",
    description:
      "A steep-sided sanctuary route that climbs from village terraces into a close Himalayan amphitheatre.",
    url: "/treks/annapurna-base-camp",
    tags: [
      "Annapurna",
      "7–11 days",
      "Moderate to challenging",
      "Pokhara",
      "Ghandruk area",
      "Chhomrong",
      "Bamboo",
      "Deurali",
      "Machhapuchhre Base Camp",
      "Annapurna Base Camp",
      "Jhinu",
      "Pokhara",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Mardi Himal Trek",
    category: "Trek",
    description:
      "A compact forest-and-ridge trek with striking Machhapuchhre views and rapid altitude gain that should not be rushed.",
    url: "/treks/mardi-himal",
    tags: [
      "Annapurna",
      "5–8 days",
      "Moderate",
      "Pokhara",
      "Forest Camp",
      "Low Camp",
      "High Camp",
      "Upper Viewpoint",
      "Siding",
      "Pokhara",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Poon Hill Trek",
    category: "Trek",
    description:
      "Stone stairways, rhododendron forest and a celebrated dawn panorama on a flexible first Nepal trek.",
    url: "/treks/poon-hill",
    tags: [
      "Annapurna",
      "3–6 days",
      "Moderate",
      "Pokhara",
      "Ulleri",
      "Ghorepani",
      "Poon Hill",
      "Tadapani",
      "Ghandruk",
      "Pokhara",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Khopra Danda Trek",
    category: "Trek",
    description:
      "A community-lodge route to a broad ridge, often combined with a demanding day walk toward Khayar Lake.",
    url: "/treks/khopra-danda",
    tags: [
      "Annapurna",
      "7–10 days",
      "Moderate to challenging",
      "Pokhara",
      "Ghandruk",
      "Tadapani",
      "Bayeli",
      "Khopra Ridge",
      "Swantha",
      "Ghorepani",
      "Pokhara",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Tilicho Lake Trek",
    category: "Trek",
    description:
      "A high side journey from Manang to a stark alpine lake, with exposed sections and serious altitude.",
    url: "/treks/tilicho-lake",
    tags: [
      "Annapurna",
      "10–16 days",
      "Challenging",
      "Besisahar",
      "Chame",
      "Pisang",
      "Manang",
      "Khangsar",
      "Tilicho Base Camp",
      "Tilicho Lake",
      "Manang",
      "Circuit exit",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Langtang Valley Trek",
    category: "Trek",
    description:
      "A road-accessible Himalayan valley trek with forest, rebuilt villages and flexible day hikes from Kyanjin.",
    url: "/treks/langtang-valley",
    tags: [
      "Langtang",
      "7–10 days",
      "Moderate",
      "Syabrubesi",
      "Lama Hotel",
      "Langtang Village",
      "Kyanjin Gompa",
      "Kyanjin day walk",
      "Langtang Village",
      "Syabrubesi",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Gosaikunda Trek",
    category: "Trek",
    description:
      "A sacred-lake trek with a fast climb and an optional high pass linking toward Helambu.",
    url: "/treks/gosaikunda",
    tags: [
      "Langtang",
      "5–8 days",
      "Moderate to challenging",
      "Dhunche",
      "Chandanbari",
      "Laurebina",
      "Gosaikunda",
      "Ghopte",
      "Kutumsang",
      "Sundarijal",
    ],
    image: "/assets/nepal-rara.webp",
  },
  {
    title: "Helambu Trek",
    category: "Trek",
    description:
      "A culturally rich ridge-and-village route close to Kathmandu, adaptable as a standalone trek or Langtang link.",
    url: "/treks/helambu",
    tags: [
      "Langtang",
      "5–8 days",
      "Moderate",
      "Sundarijal",
      "Chisapani",
      "Kutumsang",
      "Tharepati",
      "Tarke Ghyang",
      "Sermathang",
      "Melamchi",
    ],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Manaslu Circuit Trek",
    category: "Trek",
    description:
      "A long, restricted circuit from river gorges to Larkya La and the forested Marsyangdi side.",
    url: "/treks/manaslu-circuit",
    tags: [
      "Manaslu",
      "14–18 days",
      "Challenging",
      "Machha Khola",
      "Jagat",
      "Deng",
      "Namrung",
      "Samagaun",
      "Samdo",
      "Dharamsala",
      "Larkya La",
      "Bimthang",
      "Dharapani",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Tsum Valley Trek",
    category: "Trek",
    description:
      "A quieter restricted valley known for monasteries, long village approaches and Tibetan Buddhist heritage.",
    url: "/treks/tsum-valley",
    tags: [
      "Manaslu",
      "14–20 days",
      "Challenging",
      "Machha Khola",
      "Jagat",
      "Lokpa",
      "Chumling",
      "Chhokang Paro",
      "Nile",
      "Mu Gompa area",
      "Chumling",
      "Jagat",
      "Roadhead",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Upper Mustang Trek",
    category: "Trek",
    description:
      "A supported trek through wind-carved high desert to Lo Manthang and the cultural landscapes beyond.",
    url: "/treks/upper-mustang",
    tags: [
      "Mustang",
      "10–14 days",
      "Challenging",
      "Jomsom",
      "Kagbeni",
      "Chele",
      "Ghami",
      "Tsarang",
      "Lo Manthang",
      "Chhoser",
      "Dhakmar",
      "Kagbeni",
      "Jomsom",
    ],
    image: "/assets/nepal-mustang.webp",
  },
  {
    title: "Kathmandu to Pokhara",
    category: "Route",
    description:
      "Nepal’s classic intercity journey, made better by choosing the right transport—and better still by slowing down.",
    url: "/routes/kathmandu-pokhara",
    tags: [
      "Kathmandu",
      "Trishuli corridor",
      "Pokhara",
      "Tourist bus, domestic flight or private vehicle",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Kathmandu → Chitwan → Pokhara",
    category: "Route",
    description:
      "The most balanced first Nepal route links heritage, lowland wildlife and the Annapurna gateway.",
    url: "/routes/kathmandu-chitwan-pokhara",
    tags: [
      "Kathmandu",
      "Chitwan",
      "Pokhara",
      "Tourist bus or private vehicle; flights on selected legs",
    ],
    image: "/assets/nepal-chitwan.webp",
  },
  {
    title: "Kathmandu → Bandipur → Pokhara",
    category: "Route",
    description:
      "Turn the transfer west into a journey with a hill-town pause and time for ridge walking.",
    url: "/routes/kathmandu-bandipur-pokhara",
    tags: [
      "Kathmandu",
      "Dumre",
      "Bandipur",
      "Pokhara",
      "Tourist bus plus local jeep, or private vehicle",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Kathmandu → Pokhara → Ghandruk",
    category: "Route",
    description:
      "A first-timer route that moves naturally from culture to lakeside recovery and a short village trek.",
    url: "/routes/kathmandu-pokhara-ghandruk",
    tags: [
      "Kathmandu",
      "Pokhara",
      "Ghandruk",
      "Pokhara",
      "Bus or flight, then jeep and walking",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Everest Base Camp Route",
    category: "Route",
    description:
      "A complete door-to-door plan that includes flight buffers, acclimatisation and the return from Lukla.",
    url: "/routes/everest-base-camp",
    tags: [
      "Kathmandu",
      "Lukla",
      "Namche Bazaar",
      "Dingboche",
      "Everest Base Camp",
      "Lukla",
      "Flight or long overland approach, then walking",
    ],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Annapurna Circuit Route",
    category: "Route",
    description:
      "A modern circuit plan that accounts for road sections, acclimatisation and a finish in Pokhara.",
    url: "/routes/annapurna-circuit",
    tags: [
      "Kathmandu",
      "Besisahar",
      "Manang",
      "Thorong La",
      "Muktinath",
      "Pokhara",
      "Bus or jeep to and from trailheads",
    ],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "The Mustang Route",
    category: "Route",
    description:
      "A restricted high-desert journey built around permits, village stays and transport contingency.",
    url: "/routes/mustang-route",
    tags: [
      "Pokhara",
      "Jomsom",
      "Kagbeni",
      "Tsarang",
      "Lo Manthang",
      "Jomsom",
      "Flight or road to Jomsom; jeep and/or trekking",
    ],
    image: "/assets/nepal-mustang.webp",
  },
  {
    title: "Pokhara → Jomsom → Muktinath",
    category: "Route",
    description:
      "A dramatic road-or-air journey up the Kali Gandaki with pilgrimage, Thakali villages and high-desert scenery.",
    url: "/routes/pokhara-jomsom-muktinath",
    tags: [
      "Pokhara",
      "Jomsom",
      "Marpha",
      "Kagbeni",
      "Muktinath",
      "Flight, bus or jeep; short walks",
    ],
    image: "/assets/nepal-mustang.webp",
  },
  {
    title: "3 Days in Nepal",
    category: "Itinerary",
    description:
      "A compact Kathmandu Valley plan that avoids losing most of the trip to transfers.",
    url: "/itineraries/3-days",
    tags: ["A quick Nepal escape", "Kathmandu Valley", "3 day Nepal itinerary"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "5 Days in Nepal",
    category: "Itinerary",
    description:
      "Pair Kathmandu with Pokhara only if timings are realistic—or stay in the valley for a deeper, lower-impact trip.",
    url: "/itineraries/5-days",
    tags: [
      "Mountains + culture",
      "Kathmandu",
      "Pokhara",
      "5 day Nepal itinerary",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "7 Days in Nepal",
    category: "Itinerary",
    description:
      "A week with two bases, strong contrast and enough weather flexibility to enjoy both.",
    url: "/itineraries/7-days",
    tags: ["Classic Nepal", "Kathmandu", "Pokhara", "7 day Nepal itinerary"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "10 Days in Nepal",
    category: "Itinerary",
    description:
      "Add Chitwan or Bandipur without turning every day into a transfer.",
    url: "/itineraries/10-days",
    tags: [
      "Nepal beyond the highlights",
      "Kathmandu",
      "Chitwan",
      "Pokhara",
      "10 day Nepal itinerary",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "14 Days in Nepal",
    category: "Itinerary",
    description:
      "Two weeks opens the door to a short trek or a quieter overland loop.",
    url: "/itineraries/14-days",
    tags: [
      "A deeper Nepal journey",
      "Kathmandu",
      "Bandipur",
      "Pokhara",
      "Ghandruk",
      "14 day Nepal itinerary",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "21 Days in Nepal",
    category: "Itinerary",
    description:
      "Three weeks supports real acclimatisation, a major trek and a meaningful cultural beginning and end.",
    url: "/itineraries/21-days",
    tags: [
      "Take the long way round",
      "Kathmandu",
      "Annapurna or Everest trek",
      "Pokhara",
      "21 day Nepal itinerary",
    ],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Nepal Travel Guide",
    category: "Travel guide",
    description:
      "The practical framework for planning when to go, how to move, what to budget and how to travel responsibly.",
    url: "/travel-guide/nepal-travel-guide",
    tags: ["Start here", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Travel Cost",
    category: "Travel guide",
    description:
      "A transparent way to estimate daily costs without pretending one number fits every region.",
    url: "/travel-guide/nepal-travel-cost",
    tags: ["Budget", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Best Time to Visit Nepal",
    category: "Travel guide",
    description:
      "Month-by-month planning for visibility, heat, monsoon, festivals and trekking conditions.",
    url: "/travel-guide/best-time-to-visit-nepal",
    tags: ["Seasons", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Transportation",
    category: "Travel guide",
    description:
      "How to compare flights, tourist buses, local buses, jeeps, taxis and private vehicles.",
    url: "/travel-guide/nepal-transportation",
    tags: ["Getting around", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Visa",
    category: "Travel guide",
    description:
      "A plain-language planning guide with links to official immigration information.",
    url: "/travel-guide/nepal-visa",
    tags: ["Entry", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Currency & Money",
    category: "Travel guide",
    description:
      "Cash, cards, ATMs, exchange and practical payment planning across Nepal.",
    url: "/travel-guide/nepal-currency",
    tags: ["Money", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal SIM & eSIM",
    category: "Travel guide",
    description:
      "How to choose mobile data and keep offline backups for travel days.",
    url: "/travel-guide/nepal-sim-esim",
    tags: ["Connectivity", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Internet in Nepal",
    category: "Travel guide",
    description:
      "Realistic expectations for Wi-Fi, mobile data, charging and remote work.",
    url: "/travel-guide/nepal-internet",
    tags: ["Connectivity", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Travel Safety",
    category: "Travel guide",
    description:
      "Practical risk planning for altitude, roads, weather, crowds and everyday health.",
    url: "/travel-guide/nepal-safety",
    tags: ["Safety", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Packing List",
    category: "Travel guide",
    description:
      "A layered, route-aware list for cities, treks, monsoon and shoulder seasons.",
    url: "/travel-guide/nepal-packing-list",
    tags: ["Packing", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Travel Insurance",
    category: "Travel guide",
    description:
      "What to check for trekking altitude, evacuation, delays and planned activities.",
    url: "/travel-guide/nepal-travel-insurance",
    tags: ["Safety", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Trekking Permits",
    category: "Travel guide",
    description:
      "How national parks, conservation areas and restricted regions fit together.",
    url: "/travel-guide/nepal-trekking-permits",
    tags: ["Trekking", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Nepal Domestic Flights",
    category: "Travel guide",
    description:
      "Weather, baggage, airport changes and realistic connection planning.",
    url: "/travel-guide/nepal-domestic-flights",
    tags: ["Transport", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Tourist Buses in Nepal",
    category: "Travel guide",
    description:
      "What “tourist bus” means, how to compare services and what the road day feels like.",
    url: "/travel-guide/tourist-buses-in-nepal",
    tags: ["Transport", "Nepal planning"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Kathmandu to Pokhara",
    category: "Transport guide",
    description:
      "Tourist bus, flight, private vehicle. Road travel usually takes most of a day; flights are short but disruption-prone.",
    url: "/travel-guide/kathmandu-to-pokhara",
    tags: ["Kathmandu", "Pokhara", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Kathmandu to Chitwan",
    category: "Transport guide",
    description:
      "Tourist bus, private vehicle, flight via Bharatpur. Road travel commonly takes half to most of a day depending on traffic and the final hotel transfer.",
    url: "/travel-guide/kathmandu-to-chitwan",
    tags: ["Kathmandu", "Chitwan", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Pokhara to Chitwan",
    category: "Transport guide",
    description:
      "Tourist bus or private vehicle. A cross-country road day with variable journey time and a local transfer at the Chitwan end.",
    url: "/travel-guide/pokhara-to-chitwan",
    tags: ["Pokhara", "Chitwan", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Kathmandu to Lumbini",
    category: "Transport guide",
    description:
      "Long-distance bus, flight to Bhairahawa, private vehicle. The road journey is long; flying shortens the approach but still needs a ground transfer.",
    url: "/travel-guide/kathmandu-to-lumbini",
    tags: ["Kathmandu", "Lumbini", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Kathmandu to Bandipur",
    category: "Transport guide",
    description:
      "Bus to Dumre plus local jeep, or private vehicle. The main road reaches Dumre; the final climb is on a smaller hill road.",
    url: "/travel-guide/kathmandu-to-bandipur",
    tags: ["Kathmandu", "Bandipur", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Pokhara to Jomsom",
    category: "Transport guide",
    description:
      "Flight, bus or jeep. Flights are brief and weather-sensitive; the road is long, rough and seasonally affected.",
    url: "/travel-guide/pokhara-to-jomsom",
    tags: ["Pokhara", "Jomsom", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Kathmandu to Lukla",
    category: "Transport guide",
    description:
      "Scheduled flight, helicopter, or multi-day overland approach. Flights depend on visibility and may operate from a different Kathmandu-region airport; the overland option takes substantially longer.",
    url: "/travel-guide/kathmandu-to-lukla",
    tags: ["Kathmandu", "Lukla", "bus", "flight", "jeep", "private vehicle"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Trekking",
    category: "Experience",
    description:
      "Walk village trails, forest paths and high Himalayan routes at the pace altitude allows.",
    url: "/trekking",
    tags: ["Nepal experience"],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Safari",
    category: "Experience",
    description:
      "Explore river and grassland habitats with trained naturalists and no elephant rides.",
    url: "/wildlife",
    tags: ["Nepal experience"],
    image: "/assets/nepal-chitwan.webp",
  },
  {
    title: "Paragliding",
    category: "Experience",
    description:
      "Fly only with licensed operators in suitable wind and weather.",
    url: "/destinations/pokhara",
    tags: ["Nepal experience"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Rafting",
    category: "Experience",
    description:
      "Choose a river, season and operator around your experience—not just the photo.",
    url: "/plan-nepal",
    tags: ["Nepal experience"],
    image: "/assets/nepal-chitwan.webp",
  },
  {
    title: "Bungee & canyoning",
    category: "Experience",
    description:
      "Check operator credentials, equipment practice and insurance coverage.",
    url: "/plan-nepal",
    tags: ["Nepal experience"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Mountain flight",
    category: "Experience",
    description:
      "Treat the flight as weather-dependent and protect onward connections.",
    url: "/travel-guide/nepal-domestic-flights",
    tags: ["Nepal experience"],
    image: "/assets/nepal-everest.webp",
  },
  {
    title: "Mountain biking",
    category: "Experience",
    description:
      "Ride valley lanes and hill roads with route-aware local support.",
    url: "/destinations/kathmandu-valley",
    tags: ["Nepal experience"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Cultural experiences",
    category: "Experience",
    description:
      "Enter workshops, homes and rituals through respectful, community-led invitations.",
    url: "/culture",
    tags: ["Nepal experience"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Food experiences",
    category: "Experience",
    description:
      "Use food to understand season, migration, region and ritual—not only a dish list.",
    url: "/culture#food",
    tags: ["Nepal experience"],
    image: "/assets/nepal-lumbini.webp",
  },
  {
    title: "Village stays",
    category: "Experience",
    description:
      "Stay longer, ask how money is shared and adapt to household rhythms.",
    url: "/responsible-travel",
    tags: ["Nepal experience"],
    image: "/assets/nepal-annapurna.webp",
  },
  {
    title: "Photography",
    category: "Experience",
    description:
      "Plan for light, permission and context before reaching for the camera.",
    url: "/responsible-travel#photography",
    tags: ["Nepal experience"],
    image: "/assets/nepal-mustang.webp",
  },
  {
    title: "Culture in Nepal",
    category: "Culture",
    description:
      "People, festivals, food and heritage with context and respect.",
    url: "/culture",
    tags: [
      "Newar",
      "Sherpa",
      "Tharu",
      "Tamang",
      "Gurung",
      "Magar",
      "Mithila",
      "Thakali",
      "momo",
      "dal bhat",
      "festivals",
    ],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Wildlife in Nepal",
    category: "Wildlife",
    description:
      "Ethical wildlife travel in Chitwan, Bardia, Koshi Tappu, Parsa and Banke.",
    url: "/wildlife",
    tags: ["rhino", "tiger", "birds", "safari", "Chitwan", "Bardia"],
    image: "/assets/nepal-chitwan.webp",
  },
  {
    title: "Responsible Travel in Nepal",
    category: "Guide",
    description:
      "Practical choices for community benefit, less waste and respectful travel.",
    url: "/responsible-travel",
    tags: ["ethical", "plastic", "photography", "animal welfare", "homestay"],
    image: "/assets/nepal-rara.webp",
  },
  {
    title: "Plan My Nepal Trip",
    category: "Tool",
    description:
      "Build a suggested itinerary from your days, interests and trekking ability.",
    url: "/plan-my-trip",
    tags: ["trip planner", "route planner", "itinerary"],
    image: "/assets/nepal-pokhara.webp",
  },
  {
    title: "Nepal Trip Cost Calculator",
    category: "Tool",
    description: "Estimate budget, mid-range and premium Nepal trip costs.",
    url: "/tools/nepal-trip-cost",
    tags: ["budget", "travel cost", "NPR", "calculator"],
    image: "/assets/nepal-kathmandu.webp",
  },
  {
    title: "Traveler Reviews",
    category: "Community",
    description:
      "Share a moderated, independent review with route, timing and practical context.",
    url: "/reviews",
    tags: ["reviews", "traveler feedback", "Nepal trip experience"],
    image: "/assets/nepal-annapurna.webp",
  },
];
